* Using AL2 from public ECR to avoid rate limiting * Using an ARG for base image of build, allowing fast on-the-fly change * Add the AWS RDS CA on the machine and in keystore

diff --git a/16/slim/alpine/Dockerfile b/16/slim/alpine/Dockerfile
--- a/16/slim/alpine/Dockerfile
+++ b/16/slim/alpine/Dockerfile
@@ -1,5 +1,5 @@
-FROM alpine:3.12
-
+ARG BASE_IMAGE=alpine:3.14
+FROM $BASE_IMAGE
 ARG version=16.0.2.7.1
 
 # Please note that the THIRD-PARTY-LICENSE could be out of date if the base image has been updated recently. 
@@ -7,6 +7,7 @@ ARG version=16.0.2.7.1
 #
 # Slim:
 #   JLink is used (retaining all modules) to create a slimmer version of the JDK excluding man-pages, header files and debugging symbols - saving ~113MB.
+ADD https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem /usr/local/share/ca-certificates/
 RUN wget -O /THIRD-PARTY-LICENSES-20200824.tar.gz https://corretto.aws/downloads/resources/licenses/alpine/THIRD-PARTY-LICENSES-20200824.tar.gz && \
     echo "82f3e50e71b2aee21321b2b33de372feed5befad6ef2196ddec92311bc09becb  /THIRD-PARTY-LICENSES-20200824.tar.gz" | sha256sum -c - && \
     tar x -ovzf THIRD-PARTY-LICENSES-20200824.tar.gz && \
@@ -20,7 +21,9 @@ RUN wget -O /THIRD-PARTY-LICENSES-20200824.tar.gz https://corretto.aws/downloads
     apk del binutils amazon-corretto-16 && \
     mkdir -p /usr/lib/jvm/ && \
     mv /opt/corretto-slim /usr/lib/jvm/java-16-amazon-corretto && \
-    ln -sfn /usr/lib/jvm/java-16-amazon-corretto /usr/lib/jvm/default-jvm
+    ln -sfn /usr/lib/jvm/java-16-amazon-corretto /usr/lib/jvm/default-jvm  ;\
+    PATH=$PATH:/usr/lib/jvm/default-jvm/bin keytool -importcert -file /usr/local/share/ca-certificates/rds-combined-ca-bundle.pem \
+       	    -keystore cacerts -storepass changeit -trustcacerts -noprompt || echo "FAILED to add RDS CA"
 
     
 
diff --git a/16/slim/debian/Dockerfile b/16/slim/debian/Dockerfile
--- a/16/slim/debian/Dockerfile
+++ b/16/slim/debian/Dockerfile
@@ -1,4 +1,5 @@
-FROM debian:buster-slim
+ARG BASE_IMAGE=debian:buster-slim
+FROM $BASE_IMAGE
 
 ARG version=16.0.2.7-1
 # In addition to installing the Amazon corretto, we also install
@@ -12,6 +13,8 @@ ARG version=16.0.2.7-1
 #
 # Slim:
 #   JLink is used (retaining all modules) to create a slimmer version of the JDK excluding man-pages, header files and debugging symbols - saving ~113MB.
+
+ADD https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem /etc/ssl/certs/
 RUN set -ux \
     && apt-get update \
     && apt-get install -y --no-install-recommends \
@@ -30,7 +33,9 @@ RUN set -ux \
     && priority=$(echo "1${version}" | sed "s/\(\.\|-\)//g") \
     && for i in ${jdk_tools}; do \
           update-alternatives --install /usr/bin/$i $i /usr/lib/jvm/java-16-amazon-corretto/bin/$i ${priority}; \
-       done
+       done ;\
+    keytool -importcert -file /etc/ssl/certs/rds-combined-ca-bundle.pem \
+       	    -keystore cacerts -storepass changeit -trustcacerts -noprompt || echo "FAILED to add RDS CA"
 
 
 ENV LANG C.UTF-8
diff --git a/17/jdk/alpine/3.14/Dockerfile b/17/jdk/alpine/3.14/Dockerfile
--- a/17/jdk/alpine/3.14/Dockerfile
+++ b/17/jdk/alpine/3.14/Dockerfile
@@ -1,9 +1,10 @@
-FROM alpine:3.14
-
+ARG BASE_IMAGE=alpine:3.14
+FROM $BASE_IMAGE
 ARG version=17.0.0.35.1
 
-# Please note that the THIRD-PARTY-LICENSE could be out of date if the base image has been updated recently. 
+# Please note that the THIRD-PARTY-LICENSE could be out of date if the base image has been updated recently.
 # The Corretto team will update this file but you may see a few days' delay.
+ADD https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem /usr/local/share/ca-certificates/
 RUN wget -O /THIRD-PARTY-LICENSES-20200824.tar.gz https://corretto.aws/downloads/resources/licenses/alpine/THIRD-PARTY-LICENSES-20200824.tar.gz && \
     echo "82f3e50e71b2aee21321b2b33de372feed5befad6ef2196ddec92311bc09becb  /THIRD-PARTY-LICENSES-20200824.tar.gz" | sha256sum -c - && \
     tar x -ovzf THIRD-PARTY-LICENSES-20200824.tar.gz && \
@@ -12,11 +13,11 @@ RUN wget -O /THIRD-PARTY-LICENSES-20200824.tar.gz https://corretto.aws/downloads
     SHA_SUM="6cfdf08be09f32ca298e2d5bd4a359ee2b275765c09b56d514624bf831eafb91" && \
     echo "${SHA_SUM}  /etc/apk/keys/amazoncorretto.rsa.pub" | sha256sum -c - && \
     echo "https://apk.corretto.aws" >> /etc/apk/repositories && \
-    apk add --no-cache amazon-corretto-17=$version-r0
-    
-ENV LANG C.UTF-8
+    apk add --no-cache amazon-corretto-17=$version-r0 ;\
+    PATH=$PATH:/usr/lib/jvm/default-jvm/bin keytool -importcert -file /usr/local/share/ca-certificates/rds-combined-ca-bundle.pem \
+       	    -keystore cacerts -storepass changeit -trustcacerts -noprompt || echo "FAILED to add RDS CA"
 
+
+ENV LANG C.UTF-8
 ENV JAVA_HOME=/usr/lib/jvm/default-jvm
 ENV PATH=$PATH:/usr/lib/jvm/default-jvm/bin
-
-    
